import React, {useState} from 'react';
import Link from '@docusaurus/Link';
import Layout from '@theme/Layout';
import useBaseUrl from '@docusaurus/useBaseUrl';
import styles from './styles.module.css';

type Language = 'es' | 'en';
type Program = {title: string; level: string; complexity: number; description: string; meta: string[]; image: string; available?: boolean; href?: string; studentHref?: string};
type Level = {slug: string; tag: [string, string]; title: [string, string]; intro: [string, string]; image: string; theme: string; programs: Program[]};

const levels: Record<string, Level> = {
  explorador: {slug: 'explorador', tag: ['Nivel explorador', 'Explorer level'], title: ['Primeras experiencias para descubrir tecnología', 'First experiences to discover technology'], intro: ['Una ruta visual y amigable para introducir pensamiento lógico, juego guiado y tecnología aplicada desde edades tempranas.', 'A visual and approachable pathway to introduce logical thinking, guided play, and applied technology from an early stage.'], image: '/assets/platform/levels/explorador.png', theme: 'explorer', programs: [
    {title: 'Circuitos en Acción', level: 'Novato', complexity: 1, description: 'Exploración temprana de electrónica con Snap Circuits para entender energía, conexiones y causa-efecto de forma concreta.', meta: ['Snap Circuits', 'Introducción', 'Electrónica'], image: '/assets/platform/programs/explorador-circuitos.png'},
    {title: 'Rutas con Tale-Bot', level: 'Novato', complexity: 1, description: 'Retos de secuencias, direcciones y resolución de caminos para preprimaria y primeros grados con robótica tangible.', meta: ['Tale-Bot', 'Secuencias', 'Pensamiento lógico'], image: '/assets/platform/programs/explorador-talebot.png'},
    {title: 'Mundo Aumentado', level: 'Geek', complexity: 2, description: 'Experiencias iniciales de realidad aumentada para observar, interactuar y aprender con objetos digitales desde dispositivos móviles.', meta: ['Realidad aumentada', 'Visual', 'Móvil'], image: '/assets/platform/programs/explorador-ar.png'},
  ]},
  constructor: {slug: 'constructor', tag: ['Nivel constructor', 'Builder level'], title: ['Robótica aplicada y desafíos del mundo real', 'Applied robotics and real-world challenges'], intro: ['Programas donde el estudiante construye, programa, prueba y mejora soluciones con una intención técnica clara.', 'Programs where students build, program, test, and improve solutions with a clear technical purpose.'], image: '/assets/platform/levels/constructor.png', theme: 'builder', programs: [
    {title: 'CiudadBots Guatemala', level: 'Geek', complexity: 2, description: 'Ruta de robótica aplicada para ciclo básico con retos urbanos, programación, construcción, evaluación y acompañamiento docente.', meta: ['12 módulos', 'LEGO SPIKE Prime', 'Ciclo básico'], image: '/assets/platform/programs/constructor-ciudadbots.png', available: true, href: '/ciudadbots', studentHref: '/estudiante'},
    {title: 'Rescate Makerzoid', level: 'Pro', complexity: 3, description: 'Misiones de ingeniería y respuesta a retos físicos con robots modulares, maniobras, estructuras y toma de decisiones técnicas.', meta: ['Makerzoid', 'Ingeniería', 'Misiones'], image: '/assets/platform/programs/constructor-makerzoid.png'},
    {title: 'Expediciones VR', level: 'Novato', complexity: 1, description: 'Exploraciones inmersivas con Meta Quest para ciencia, tecnología e ingeniería con experiencias guiadas y reflexión aplicada.', meta: ['Meta Quest', 'Inmersivo', 'STEAM'], image: '/assets/platform/programs/constructor-vr.png'},
  ]},
  creador: {slug: 'creador', tag: ['Nivel creador', 'Creator level'], title: ['Diseño, prototipado e innovación aplicada', 'Design, prototyping, and applied innovation'], intro: ['Programas pensados para convertir ideas en prototipos, productos y experiencias con identidad propia.', 'Programs built to turn ideas into prototypes, products, and experiences with their own identity.'], image: '/assets/platform/levels/creador.png', theme: 'creator', programs: [
    {title: 'SmartLab Wearables', level: 'Pro', complexity: 3, description: 'Diseño y construcción de dispositivos vestibles como relojes inteligentes usando ESP32, Arduino, micro:bit y sensores.', meta: ['ESP32', 'Arduino', 'micro:bit'], image: '/assets/platform/programs/creador-wearables.png'},
    {title: 'Estudio IA Creativa', level: 'Geek', complexity: 2, description: 'Producción digital con inteligencia artificial, ciudadanía digital y narrativa visual para crear contenido con criterio y propósito.', meta: ['IA', 'Ciudadanía digital', 'Contenido'], image: '/assets/platform/programs/creador-ia.png'},
    {title: 'FabLab 3D', level: 'Pro', complexity: 3, description: 'Ruta de modelado, diseño 3D e impresión 3D para desarrollar prototipos funcionales, iterar y presentar soluciones tangibles.', meta: ['Diseño 3D', 'Impresión 3D', 'Prototipos'], image: '/assets/platform/programs/creador-fab3d.png'},
    {title: 'Ciudadanía Digital Lab', level: 'Novato', complexity: 1, description: 'Ruta formativa para desarrollar convivencia digital, pensamiento crítico, seguridad en línea y uso responsable de plataformas y contenidos.', meta: ['Seguridad digital', 'Huella digital', 'Criterio en línea'], image: '/assets/platform/programs/creador-ia.png'},
  ]},
};

const labels = {es: {back: 'Volver', programs: 'Programas del nivel', available: 'Disponible', upcoming: 'Próximamente', unavailable: 'Vista no disponible', open: 'Abrir programa', student: 'Modo estudiante', level: 'Nivel del Programa'}, en: {back: 'Back', programs: 'Programs in this level', available: 'Available', upcoming: 'Coming soon', unavailable: 'Preview unavailable', open: 'Open program', student: 'Student mode', level: 'Program Level'}};

function Meter({value}: {value: number}): React.JSX.Element { return <span className={styles.complexityBars} aria-label={`Complexity ${value} of 3`}>{[1, 2, 3].map((step) => <i className={step <= value ? styles.active : ''} key={step} />)}</span>; }

function ProgramCard({program, language}: {program: Program; language: Language}): React.JSX.Element {
  const t = labels[language];
  return <article className={`${styles.programCard} ${!program.available ? styles.disabled : ''}`}><div className={styles.cardMedia}><img src={useBaseUrl(program.image)} alt={program.title} /><span className={`${styles.cardState} ${program.available ? styles.ready : ''}`}>{program.available ? t.available : t.upcoming}</span></div><div className={styles.cardBody}><span className={styles.levelChip}>{t.level}: {program.level}</span><div className={styles.titleRow}><h3>{program.title}</h3><Meter value={program.complexity} /></div><p>{program.description}</p><div className={styles.meta}>{program.meta.map((item) => <span key={item}>{item}</span>)}</div><div className={styles.ctaRow}>{program.href ? <><Link className={styles.cta} to={program.href}>{t.open}</Link>{program.studentHref && <Link className={styles.ghost} to={program.studentHref}>{t.student}</Link>}</> : <span className={`${styles.ghost} ${styles.disabledButton}`}>{t.unavailable}</span>}</div></div></article>;
}

export default function LevelCatalog({levelKey}: {levelKey: keyof typeof levels}): React.JSX.Element {
  const [language, setLanguage] = useState<Language>('es');
  const level = levels[levelKey]; const t = labels[language];
  return <Layout title={`GuateGeeks · ${level.title[language === 'es' ? 0 : 1]}`}><main className={`${styles.page} ${styles[level.theme]}`}><div className={styles.wrap}><div className={styles.toprow}><Link className={styles.back} to="/">{t.back}</Link><div className={styles.langSwitch}><button className={language === 'es' ? styles.active : ''} type="button" onClick={() => setLanguage('es')}>ES</button><button className={language === 'en' ? styles.active : ''} type="button" onClick={() => setLanguage('en')}>EN</button></div></div><section className={styles.hero}><img src={useBaseUrl(level.image)} alt={level.tag[language === 'es' ? 0 : 1]} /><div className={styles.heroCopy}><span className={styles.tag}>{level.tag[language === 'es' ? 0 : 1]}</span><h1>{level.title[language === 'es' ? 0 : 1]}</h1><p>{level.intro[language === 'es' ? 0 : 1]}</p></div></section><div className={styles.sectionHead}><div><h2>{t.programs}</h2><p>{levelKey === 'constructor' ? (language === 'es' ? 'Aquí se visualiza el portafolio de proyectos del nivel constructor. CiudadBots está disponible y los demás se muestran como próximos programas para completar la oferta.' : 'This page shows the builder project portfolio. CiudadBots is available and the others are upcoming programs to complete the offer.') : (language === 'es' ? 'Estos programas funcionan como vitrina del ecosistema GuateGeeks y muestran la ruta de crecimiento de cada nivel.' : 'These programs showcase the GuateGeeks ecosystem and show each level\'s growth path.')}</p></div></div><section className={styles.programGrid}>{level.programs.map((program) => <ProgramCard key={program.title} program={program} language={language} />)}</section></div></main></Layout>;
}
