import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// One sidebar per program. Each is auto-generated from that program's own
// subdirectory of docs/, which also supplies the program's URL segment
// (docs/ciudadbots/* -> /ciudadbots/*). Adding a program means adding a
// directory and a sidebar here, without touching the existing ones.
const sidebars: SidebarsConfig = {
  ciudadbotsSidebar: [{type: 'autogenerated', dirName: 'ciudadbots'}],
  guategeeksSidebar: [
    'guategeeks/index',
    'guategeeks/sistemas-del-robot',
    'guategeeks/seguridad-y-energia',
    'guategeeks/slicer-y-tolerancias',
    'guategeeks/impresion-y-control-de-calidad',
    'guategeeks/ensamblaje-de-orugas',
    'guategeeks/botones-y-buzzer',
    'guategeeks/dos-motores-y-direccion',
    'guategeeks/sensor-ultrasonico',
    'guategeeks/lectura-de-codigo',
    'guategeeks/integracion-autonoma',
    'guategeeks/calibracion',
    'guategeeks/reto-integrador',
    'guategeeks/showcase',
    'guategeeks/rubrica',
  ],
  tiempoCircularSidebar: [{type: 'autogenerated', dirName: 'tiempo-circular'}],
};

export default sidebars;
