import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// One sidebar per program. Each is auto-generated from that program's own
// subdirectory of docs/, which also supplies the program's URL segment
// (docs/ciudadbots/* -> /ciudadbots/*). Adding a program means adding a
// directory and a sidebar here, without touching the existing ones.
const sidebars: SidebarsConfig = {
  ciudadbotsSidebar: [{type: 'autogenerated', dirName: 'ciudadbots'}],
  guategeeksSidebar: [{type: 'autogenerated', dirName: 'guategeeks'}],
};

export default sidebars;
