import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// One sidebar scoped to the CiudadBots program, auto-generated from the docs
// folder. A future program would add its own sidebar (or docs instance) here
// without touching this one.
const sidebars: SidebarsConfig = {
  ciudadbotsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
